spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-test.xml