server:
  port: 8181

spring:
  profiles:
    active: dev
#    active: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
    url: swagger.yaml
    try-it-out-enabled: false
    syntax-highlight:
      activated: true